/**
 * Medical Report Simplifier engine.
 *
 * Implements the pipeline described in `docs/report-simplifier.md`:
 *
 *   upload -> simulated OCR -> biomarker dictionary match -> normalisation and
 *   reference-range scoring -> plain-language translation -> longitudinal
 *   history linking.
 *
 * The OCR step is simulated on purpose: this prototype ships with zero backend
 * and zero paid services, so no text-recognition provider is contacted. Files
 * that already contain text (.txt / .csv) are read directly; everything else
 * (PDF, PNG, JPG) resolves to a synthetic OCR transcript for the selected panel
 * category and reports a simulated confidence score.
 *
 * Nothing in this module asserts a diagnosis. Every explanation states what the
 * biomarker measures and how the result sits against its reference range.
 */

import type {
  BiomarkerCategory,
  BiomarkerStatus,
  BiomarkerTrend,
  ExtractedField,
  MedicalReport,
  ReferenceRange,
  ReportCategory,
  TrendPoint,
} from "@/types";

/** Immutable notice attached to every screen and export in the simplifier. */
export const MEDICAL_DISCLAIMER =
  "IMPORTANT MEDICAL DISCLAIMER: This document is an educational explanation generated by " +
  "SmartMedic AI to explain clinical terms, values, and reference ranges in everyday language. " +
  "It does not provide medical diagnoses, treatment recommendations, or clinical prognoses. " +
  "Lab values must always be evaluated in the context of your complete medical history by your " +
  "attending physician. Do not start, stop, or modify any medication without consulting your doctor.";

/* ------------------------------------------------------------------ */
/* Biomarker dictionary                                                */
/* ------------------------------------------------------------------ */

export interface BiomarkerDefinition {
  /** Normalised key persisted alongside every extracted field. */
  key: string;
  displayName: string;
  /** Raw spellings this key absorbs; matched longest-first. */
  aliases: string[];
  unit: string;
  min: number;
  max: number;
  criticalLow?: number;
  criticalHigh?: number;
  category: BiomarkerCategory;
  /** What the biomarker measures, in everyday language. */
  measures: string;
  /** Appended when the value sits above the reference range. */
  highNote: string;
  /** Appended when the value sits below the reference range. */
  lowNote: string;
}

/**
 * The clinical dictionary. Aliases are deliberately written in the messy forms
 * that appear on real lab printouts (Hb/Hgb, SGPT, PLT) so the matcher works on
 * layout-drifted OCR output rather than on tidy input.
 */
export const BIOMARKER_DICTIONARY: BiomarkerDefinition[] = [
  {
    key: "fbs",
    displayName: "Fasting Blood Sugar (FBS)",
    aliases: ["fasting blood sugar", "glucose fasting", "fasting glucose", "fbs", "gtt fasting"],
    unit: "mg/dL",
    min: 70,
    max: 99,
    criticalLow: 54,
    criticalHigh: 250,
    category: "glycemic",
    measures: "the amount of glucose (sugar) circulating in your blood after at least 8 hours without food.",
    highNote:
      "A fasting reading above the reference range means your body is holding onto more glucose than expected while at rest.",
    lowNote:
      "A fasting reading below the reference range means blood glucose is running low, which can cause shakiness, sweating, or dizziness.",
  },
  {
    key: "ppbs",
    displayName: "Post Prandial Blood Sugar (PPBS)",
    aliases: ["post prandial blood sugar", "postprandial glucose", "2 hour post prandial", "ppbs", "pp glucose"],
    unit: "mg/dL",
    min: 70,
    max: 140,
    criticalHigh: 300,
    category: "glycemic",
    measures: "your blood glucose measured about two hours after a meal, when the peak effect of that meal is visible.",
    highNote: "A post-meal reading above the reference range shows glucose is clearing more slowly than expected after eating.",
    lowNote: "A post-meal reading below the reference range is unusual and is usually read together with the fasting value.",
  },
  {
    key: "rbs",
    displayName: "Random Blood Sugar (RBS)",
    aliases: ["random blood sugar", "random glucose", "rbs"],
    unit: "mg/dL",
    min: 70,
    max: 140,
    criticalLow: 54,
    criticalHigh: 300,
    category: "glycemic",
    measures: "a glucose reading taken at any point in the day, without any fasting requirement.",
    highNote: "A random reading above the reference range is a snapshot only and is normally confirmed with a fasting test.",
    lowNote: "A random reading below the reference range suggests low blood glucose at the moment of sampling.",
  },
  {
    key: "hba1c",
    displayName: "Glycated Hemoglobin (HbA1c)",
    aliases: ["glycated hemoglobin", "glycosylated hemoglobin", "hemoglobin a1c", "haemoglobin a1c", "hba1c", "a1c"],
    unit: "%",
    min: 4.0,
    max: 5.6,
    criticalHigh: 10,
    category: "glycemic",
    measures:
      "your average blood sugar over the past two to three months, by measuring how much sugar has attached to your red blood cells.",
    highNote:
      "A value above the reference range reflects a higher average blood sugar over the last few months rather than a single bad day.",
    lowNote: "A value below the reference range reflects a lower long-term average blood sugar.",
  },
  {
    key: "creatinine",
    displayName: "Serum Creatinine",
    aliases: ["serum creatinine", "creatinine serum", "s. creatinine", "creatinine", "creat"],
    unit: "mg/dL",
    min: 0.7,
    max: 1.3,
    criticalHigh: 4.0,
    category: "renal",
    measures: "a natural waste product from normal muscle activity that your kidneys filter out into urine.",
    highNote:
      "A value above the reference range can mean the kidneys are clearing this waste more slowly than expected. Hydration, muscle mass, and some medicines all influence the number.",
    lowNote: "A value below the reference range is often related to lower muscle mass and is frequently not meaningful on its own.",
  },
  {
    key: "urea",
    displayName: "Blood Urea",
    aliases: ["blood urea nitrogen", "blood urea", "urea nitrogen", "bun", "urea"],
    unit: "mg/dL",
    min: 7,
    max: 20,
    criticalHigh: 100,
    category: "renal",
    measures: "a nitrogen-containing waste product from protein breakdown that the kidneys remove from the blood.",
    highNote: "A value above the reference range can follow dehydration, a high protein intake, or slower kidney clearance.",
    lowNote: "A value below the reference range is commonly linked to a low protein intake or liver function.",
  },
  {
    key: "egfr",
    displayName: "Estimated GFR (eGFR)",
    aliases: ["estimated gfr", "estimated glomerular filtration rate", "egfr", "gfr"],
    unit: "mL/min/1.73m2",
    min: 90,
    max: 120,
    criticalLow: 15,
    category: "renal",
    measures: "an estimate of how much blood your kidneys filter each minute, calculated from creatinine and your age.",
    highNote: "A value above the reference range is generally not a concern; filtration above the expected level is normal.",
    lowNote: "A value below the reference range suggests the kidneys are filtering more slowly than expected for your age.",
  },
  {
    key: "hemoglobin",
    displayName: "Hemoglobin (Hb)",
    aliases: ["haemoglobin", "hemoglobin", "hgb", "hb"],
    unit: "g/dL",
    min: 13.5,
    max: 17.5,
    criticalLow: 7,
    category: "hematology",
    measures: "the oxygen-carrying protein inside red blood cells that moves air from your lungs to the rest of your body.",
    highNote: "A value above the reference range can follow dehydration or long-term low oxygen levels.",
    lowNote: "A value below the reference range reduces the blood's oxygen-carrying capacity and is the usual finding in anaemia.",
  },
  {
    key: "platelets",
    displayName: "Platelet Count (PLT)",
    aliases: ["platelet count", "platelets", "plt"],
    unit: "×10³/µL",
    min: 150,
    max: 450,
    criticalLow: 50,
    criticalHigh: 1000,
    category: "hematology",
    measures: "tiny cell fragments in the blood that clump together to seal cuts and stop bleeding.",
    highNote: "A count above the reference range can follow inflammation, infection, or iron deficiency.",
    lowNote: "A count below the reference range means the blood clots less readily, so bruising and bleeding take longer to stop.",
  },
  {
    key: "wbc",
    displayName: "Total Leukocyte Count (TLC)",
    aliases: ["total leukocyte count", "total white blood cell count", "white blood cell count", "leukocyte count", "wbc", "tlc"],
    unit: "×10³/µL",
    min: 4.0,
    max: 11.0,
    criticalLow: 2,
    criticalHigh: 30,
    category: "hematology",
    measures: "the number of infection-fighting white cells circulating in your blood.",
    highNote: "A count above the reference range usually accompanies the body responding to an infection or inflammation.",
    lowNote: "A count below the reference range means fewer infection-fighting cells are available.",
  },
  {
    key: "rbc",
    displayName: "Red Blood Cell Count (RBC)",
    aliases: ["red blood cell count", "rbc count", "erythrocyte count", "rbc"],
    unit: "million/µL",
    min: 4.5,
    max: 5.9,
    category: "hematology",
    measures: "the total number of oxygen-carrying red cells in a measured volume of blood.",
    highNote: "A count above the reference range can be a response to low oxygen or dehydration.",
    lowNote: "A count below the reference range is commonly seen alongside a low hemoglobin.",
  },
  {
    key: "hematocrit",
    displayName: "Hematocrit (HCT)",
    aliases: ["packed cell volume", "hematocrit", "haematocrit", "hct", "pcv"],
    unit: "%",
    min: 40,
    max: 52,
    category: "hematology",
    measures: "the percentage of your blood volume made up of red blood cells.",
    highNote: "A value above the reference range can follow dehydration or a raised red cell count.",
    lowNote: "A value below the reference range usually tracks with a low hemoglobin.",
  },
  {
    key: "mcv",
    displayName: "Mean Corpuscular Volume (MCV)",
    aliases: ["mean corpuscular volume", "mean cell volume", "mcv"],
    unit: "fL",
    min: 80,
    max: 100,
    category: "hematology",
    measures: "the average size of your red blood cells, which helps describe the type of any anaemia.",
    highNote: "Larger than expected red cells are often associated with vitamin B12 or folate levels.",
    lowNote: "Smaller than expected red cells are often associated with iron levels.",
  },
  {
    key: "tsh",
    displayName: "Thyroid Stimulating Hormone (TSH)",
    aliases: ["thyroid stimulating hormone", "thyrotropin", "tsh"],
    unit: "µIU/mL",
    min: 0.4,
    max: 4.0,
    criticalHigh: 20,
    category: "thyroid",
    measures: "a signal hormone from the pituitary gland that tells your thyroid how much metabolic hormone to release.",
    highNote: "A value above the reference range means the pituitary is signalling the thyroid harder than usual.",
    lowNote: "A value below the reference range means less of that signal is being produced.",
  },
  {
    key: "t3",
    displayName: "Triiodothyronine (T3)",
    aliases: ["triiodothyronine", "total t3", "t3"],
    unit: "ng/dL",
    min: 80,
    max: 200,
    category: "thyroid",
    measures: "one of the two active thyroid hormones that set the pace of your metabolism.",
    highNote: "A value above the reference range reflects a faster metabolic setting.",
    lowNote: "A value below the reference range reflects a slower metabolic setting.",
  },
  {
    key: "t4",
    displayName: "Thyroxine (T4)",
    aliases: ["thyroxine", "total t4", "t4"],
    unit: "µg/dL",
    min: 5.0,
    max: 12.0,
    category: "thyroid",
    measures: "the main storage form of thyroid hormone, converted in the body into the active T3 form.",
    highNote: "A value above the reference range reflects more thyroid hormone circulating than expected.",
    lowNote: "A value below the reference range reflects less thyroid hormone circulating than expected.",
  },
  {
    key: "total_cholesterol",
    displayName: "Total Cholesterol",
    aliases: ["total cholesterol", "cholesterol total", "serum cholesterol", "cholesterol"],
    unit: "mg/dL",
    min: 125,
    max: 200,
    category: "lipid",
    measures: "the combined amount of all cholesterol carried in your blood, including the LDL and HDL fractions.",
    highNote: "A value above the reference range is read together with the LDL and HDL split rather than on its own.",
    lowNote: "A value below the reference range is generally not treated as a concern.",
  },
  {
    key: "ldl",
    displayName: "LDL Cholesterol",
    aliases: ["ldl cholesterol", "low density lipoprotein", "ldl-c", "ldl"],
    unit: "mg/dL",
    min: 50,
    max: 100,
    criticalHigh: 190,
    category: "lipid",
    measures: "the cholesterol fraction that deposits in artery walls when present in excess.",
    highNote: "A value above the reference range increases the cholesterol burden on the artery walls over time.",
    lowNote: "A value below the reference range is generally not treated as a concern.",
  },
  {
    key: "hdl",
    displayName: "HDL Cholesterol",
    aliases: ["hdl cholesterol", "high density lipoprotein", "hdl-c", "hdl"],
    unit: "mg/dL",
    min: 40,
    max: 60,
    criticalLow: 25,
    category: "lipid",
    measures: "the cholesterol fraction that carries excess cholesterol back to the liver for disposal.",
    highNote: "A higher value in this direction is generally regarded as favourable.",
    lowNote: "A value below the reference range means less cholesterol is being carried back for disposal.",
  },
  {
    key: "triglycerides",
    displayName: "Triglycerides",
    aliases: ["triglycerides", "triglyceride", "serum triglycerides", "tg"],
    unit: "mg/dL",
    min: 50,
    max: 150,
    criticalHigh: 500,
    category: "lipid",
    measures: "the main form of stored fat travelling in your bloodstream between meals.",
    highNote: "A value above the reference range is commonly influenced by recent food intake, alcohol, and blood sugar control.",
    lowNote: "A value below the reference range is generally not treated as a concern.",
  },
  {
    key: "alt",
    displayName: "Alanine Aminotransferase (SGPT)",
    aliases: ["alanine aminotransferase", "sgpt", "alt (sgpt)", "alt"],
    unit: "U/L",
    min: 7,
    max: 56,
    criticalHigh: 200,
    category: "hepatic",
    measures: "an enzyme mostly found in liver cells that leaks into the blood when those cells are irritated.",
    highNote: "A value above the reference range indicates liver cells are releasing more of this enzyme than usual.",
    lowNote: "A value below the reference range is generally not treated as a concern.",
  },
  {
    key: "ast",
    displayName: "Aspartate Aminotransferase (SGOT)",
    aliases: ["aspartate aminotransferase", "sgot", "ast (sgot)", "ast"],
    unit: "U/L",
    min: 10,
    max: 40,
    criticalHigh: 200,
    category: "hepatic",
    measures: "an enzyme present in liver and muscle tissue that rises in the blood when those tissues are stressed.",
    highNote: "A value above the reference range indicates tissue is releasing more of this enzyme than usual.",
    lowNote: "A value below the reference range is generally not treated as a concern.",
  },
  {
    key: "alp",
    displayName: "Alkaline Phosphatase (ALP)",
    aliases: ["alkaline phosphatase", "alp"],
    unit: "U/L",
    min: 44,
    max: 147,
    category: "hepatic",
    measures: "an enzyme linked to the bile ducts, liver, and bone turnover.",
    highNote: "A value above the reference range can relate to bile flow or to increased bone turnover.",
    lowNote: "A value below the reference range is generally not treated as a concern.",
  },
  {
    key: "total_bilirubin",
    displayName: "Total Bilirubin",
    aliases: ["total bilirubin", "bilirubin total", "serum bilirubin", "bilirubin"],
    unit: "mg/dL",
    min: 0.2,
    max: 1.2,
    criticalHigh: 10,
    category: "hepatic",
    measures: "a yellow pigment produced when old red blood cells are recycled, processed by the liver.",
    highNote: "A value above the reference range means more of this pigment is present than the liver is clearing.",
    lowNote: "A value below the reference range is generally not treated as a concern.",
  },
  {
    key: "sodium",
    displayName: "Sodium (Na+)",
    aliases: ["serum sodium", "sodium na", "sodium"],
    unit: "mmol/L",
    min: 135,
    max: 145,
    criticalLow: 120,
    criticalHigh: 160,
    category: "electrolyte",
    measures: "the main salt mineral that controls the water balance across your body's cells.",
    highNote: "A level above the reference range often follows water loss or reduced fluid intake.",
    lowNote: "A level below the reference range often follows excess water relative to salt.",
  },
  {
    key: "potassium",
    displayName: "Potassium (K+)",
    aliases: ["serum potassium", "potassium k", "potassium"],
    unit: "mmol/L",
    min: 3.5,
    max: 5.1,
    criticalLow: 2.5,
    criticalHigh: 6.5,
    category: "electrolyte",
    measures: "a mineral that carries electrical signals for your heart and muscles.",
    highNote: "A level above the reference range affects the heart's electrical rhythm and is watched closely.",
    lowNote: "A level below the reference range can cause muscle cramps and rhythm changes.",
  },
  {
    key: "calcium",
    displayName: "Total Calcium",
    aliases: ["total calcium", "serum calcium", "calcium"],
    unit: "mg/dL",
    min: 8.6,
    max: 10.2,
    criticalLow: 7,
    criticalHigh: 13,
    category: "electrolyte",
    measures: "the mineral that builds bone and drives muscle and nerve signalling.",
    highNote: "A level above the reference range can relate to parathyroid or vitamin D activity.",
    lowNote: "A level below the reference range can relate to vitamin D status.",
  },
  {
    key: "crp",
    displayName: "C-Reactive Protein (CRP)",
    aliases: ["c reactive protein", "c-reactive protein", "crp"],
    unit: "mg/L",
    min: 0,
    max: 5,
    criticalHigh: 100,
    category: "inflammatory",
    measures: "a general marker the liver releases when there is inflammation somewhere in the body.",
    highNote: "A value above the reference range shows inflammation is present, without indicating where it is.",
    lowNote: "A value within or below the reference range shows no strong inflammatory signal at the time of sampling.",
  },
  {
    key: "esr",
    displayName: "Erythrocyte Sedimentation Rate (ESR)",
    aliases: ["erythrocyte sedimentation rate", "sedimentation rate", "esr"],
    unit: "mm/hr",
    min: 0,
    max: 20,
    category: "inflammatory",
    measures: "how quickly red cells settle in a tube, which rises broadly with inflammation.",
    highNote: "A value above the reference range is a general sign of inflammation and is read alongside other results.",
    lowNote: "A value within the reference range shows no strong inflammatory signal at the time of sampling.",
  },
  {
    key: "uric_acid",
    displayName: "Uric Acid",
    aliases: ["serum uric acid", "uric acid"],
    unit: "mg/dL",
    min: 3.4,
    max: 7.0,
    category: "renal",
    measures: "a waste product from purine breakdown that the kidneys remove.",
    highNote: "A value above the reference range can relate to diet and kidney clearance.",
    lowNote: "A value below the reference range is generally not treated as a concern.",
  },
  {
    key: "vitamin_d",
    displayName: "Vitamin D (25-OH)",
    aliases: ["vitamin d 25 oh", "25 hydroxy vitamin d", "vitamin d", "25-oh-d"],
    unit: "ng/mL",
    min: 30,
    max: 100,
    criticalLow: 10,
    category: "electrolyte",
    measures: "the vitamin that controls how calcium is absorbed and used by bone.",
    highNote: "A level above the reference range can follow prolonged high-dose supplementation.",
    lowNote: "A level below the reference range reduces calcium absorption and can affect bone strength.",
  },
];

/**
 * Matching index. Aliases are sorted longest-first so `hba1c` wins over `hb` on
 * the same line, and each entry keeps both the raw alias (used to strip the
 * test name off the raw line) and the normalised needle (used to test a line).
 */
const ALIAS_INDEX: { alias: string; needle: string; definition: BiomarkerDefinition }[] =
  BIOMARKER_DICTIONARY.flatMap((definition) =>
    definition.aliases.map((alias) => ({ alias, needle: matchForm(alias), definition })),
  ).sort((a, b) => b.needle.length - a.needle.length);

export function findBiomarkerDefinition(key: string): BiomarkerDefinition | undefined {
  return BIOMARKER_DICTIONARY.find((definition) => definition.key === key);
}

/* ------------------------------------------------------------------ */
/* Line normalisation helpers                                          */
/* ------------------------------------------------------------------ */

/** Fold the unicode noise that OCR engines emit into plain ASCII. */
export function normaliseLine(raw: string): string {
  return raw
    .replace(/[\u2212\u2013\u2014]/g, "-")
    .replace(/[\u00b5\u03bc]/g, "µ")
    .replace(/\u00d7/g, "x")
    .replace(/\s+/g, " ")
    .trim();
}

/**
 * Lowercased, punctuation-free form used for dictionary matching. Hyphens and
 * slashes become spaces so `C-Reactive Protein` and `c reactive protein` are
 * the same needle.
 */
function matchForm(raw: string): string {
  return normaliseLine(raw)
    .toLowerCase()
    .replace(/[():,;/\\-]/g, " ")
    .replace(/\s+/g, " ")
    .trim();
}

/** Tolerant unit matcher: OCR is inconsistent about spacing, case and glyphs. */
const UNIT_PATTERN =
  /(mg\s*\/\s*dl|gm\s*\/\s*dl|g\s*\/\s*dl|mg\s*\/\s*l|g\s*\/\s*l|mmol\s*\/\s*l|µiu\s*\/\s*ml|uiu\s*\/\s*ml|miu\s*\/\s*ml|ng\s*\/\s*dl|µg\s*\/\s*dl|ug\s*\/\s*dl|iu\s*\/\s*l|u\s*\/\s*l|ng\s*\/\s*ml|pg\s*\/\s*ml|million\s*\/\s*[µu]l|x?\s*10\s*\^?\s*3\s*\/\s*[µu]l|ml\s*\/\s*min\s*\/\s*1\.73\s*m2|mm\s*\/\s*hr|\bfl\b|%)/i;

const NUMBER_PATTERN = /(-?\d+(?:[.,]\d+)?)/;

/** Canonical display form per normalised unit key. */
const UNIT_ALIASES: Record<string, string> = {
  "mg/dl": "mg/dL",
  "gm/dl": "g/dL",
  "g/dl": "g/dL",
  "mg/l": "mg/L",
  "g/l": "g/L",
  "mmol/l": "mmol/L",
  "miu/ml": "µIU/mL",
  "uiu/ml": "µIU/mL",
  "µiu/ml": "µIU/mL",
  "iu/l": "U/L",
  "u/l": "U/L",
  "ng/ml": "ng/mL",
  "pg/ml": "pg/mL",
  "ng/dl": "ng/dL",
  "µg/dl": "µg/dL",
  "ug/dl": "µg/dL",
  "mm/hr": "mm/hr",
  fl: "fL",
  "million/µl": "million/µL",
  "million/ul": "million/µL",
  "x10^3/µl": "×10³/µL",
  "x10^3/ul": "×10³/µL",
  "ml/min/1.73m2": "mL/min/1.73m²",
  "%": "%",
};

/**
 * Map every recognised spelling of a unit onto its single display form, so the
 * extracted field and its reference range always render the same unit.
 */
export function canonicalUnit(raw: string): string {
  const key = normaliseLine(raw).toLowerCase().replace(/\s+/g, "");
  return UNIT_ALIASES[key] ?? normaliseLine(raw);
}

function toNumber(token: string): number | null {
  const cleaned = token.replace(/,(\d{1,2})$/, ".$1").replace(/,/g, "");
  const parsed = Number(cleaned);
  return Number.isFinite(parsed) ? parsed : null;
}

/** Deterministic 32-bit hash so confidence values are stable across reloads. */
function hashString(value: string): number {
  let hash = 2166136261;
  for (let i = 0; i < value.length; i++) {
    hash ^= value.charCodeAt(i);
    hash = Math.imul(hash, 16777619);
  }
  return hash >>> 0;
}

/** Word-boundary safe test: `hb` must not match inside `hba1c`. */
function containsAlias(haystack: string, alias: string): boolean {
  let from = 0;
  for (;;) {
    const index = haystack.indexOf(alias, from);
    if (index === -1) return false;
    const before = index === 0 ? "" : haystack[index - 1];
    const after = index + alias.length >= haystack.length ? "" : haystack[index + alias.length];
    const boundary = (char: string) => char === "" || char === " " || char === "-" || char === "/";
    if (boundary(before) && boundary(after)) return true;
    from = index + 1;
  }
}

/* ------------------------------------------------------------------ */
/* Reference range scoring                                             */
/* ------------------------------------------------------------------ */

export function referenceRangeText(min: number, max: number, unit: string): string {
  const format = (value: number) => String(value);
  return `${format(min)} - ${format(max)} ${unit}`.trim();
}

export function toReferenceRange(definition: BiomarkerDefinition): ReferenceRange {
  return {
    min: definition.min,
    max: definition.max,
    text: referenceRangeText(definition.min, definition.max, definition.unit),
    criticalLow: definition.criticalLow,
    criticalHigh: definition.criticalHigh,
  };
}

/** Classify a value against its range and optional panic thresholds. */
export function scoreBiomarkerStatus(value: number, range: ReferenceRange): BiomarkerStatus {
  if (!Number.isFinite(value)) return "unknown";
  if (range.criticalHigh !== undefined && value >= range.criticalHigh) return "critical_high";
  if (range.criticalLow !== undefined && value <= range.criticalLow) return "critical_low";
  if (value > range.max) return "elevated";
  if (value < range.min) return "low";
  return "normal";
}

export function isOutOfRange(status: BiomarkerStatus): boolean {
  return status === "low" || status === "elevated" || status === "critical_low" || status === "critical_high";
}

/** Build the non-diagnostic plain-language explanation for one result. */
export function buildExplanation(
  definition: BiomarkerDefinition,
  value: number,
  unit: string,
  status: BiomarkerStatus,
): string {
  const opening = `${definition.displayName} measures ${definition.measures}`;
  const reading = `Your result was ${value} ${unit}, against a typical reference range of ${definition.min} - ${definition.max} ${unit}.`;

  if (status === "critical_low") {
    return `${opening} ${reading} This sits notably below the reference range, so ${definition.lowNote.toLowerCase()} A result in this band is normally reviewed promptly by the treating physician.`;
  }
  if (status === "critical_high") {
    return `${opening} ${reading} This sits notably above the reference range, so ${definition.highNote.toLowerCase()} A result in this band is normally reviewed promptly by the treating physician.`;
  }
  if (status === "low") {
    return `${opening} ${reading} ${definition.lowNote} This is an educational observation, not an interpretation of your condition.`;
  }
  if (status === "elevated") {
    return `${opening} ${reading} ${definition.highNote} This is an educational observation, not an interpretation of your condition.`;
  }
  if (status === "normal") {
    return `${opening} ${reading} This result falls inside the usual reference range for an adult.`;
  }
  return `${opening} ${reading} The system could not map this result to a standard reference range.`;
}

/* ------------------------------------------------------------------ */
/* Field extraction                                                    */
/* ------------------------------------------------------------------ */

/** Build a tolerant regex for an alias so `Vitamin D (25-OH)` still matches. */
function aliasRegex(alias: string): RegExp {
  const parts = alias.split(" ").map((part) => part.replace(/[.*+?^${}()|[\]\\]/g, "\\$&"));
  return new RegExp(parts.join("[\\s().,\\-/]*"), "i");
}

/**
 * Try to read one raw OCR line as a biomarker result. The row shape assumed is
 * `test name | value | unit | reference range | flag`, which is what both the
 * synthetic transcripts and real analyser printouts use.
 */
export function matchBiomarkerLine(raw: string): ExtractedField | null {
  const line = normaliseLine(raw);
  if (line.length < 4) return null;

  const haystack = matchForm(line);

  for (const { alias, needle, definition } of ALIAS_INDEX) {
    if (!containsAlias(haystack, needle)) continue;

    // Step 1: strip the test name so digits inside it (the "25" of
    // "25-OH Vitamin D", the "3" of "T3") cannot be read as the result.
    const stripped = line.replace(aliasRegex(alias), " ");

    // Step 2: cut at the reference-range column, which prints as two numbers
    // joined by a dash or the word "to".
    const rangeMatch = stripped.match(/\d+(?:\.\d+)?\s*(?:-|to)\s*\d+(?:\.\d+)?/i);
    const head =
      rangeMatch && rangeMatch.index !== undefined ? stripped.slice(0, rangeMatch.index) : stripped;

    // Step 3: drop unit glyphs, including exponent forms such as "x10^3/uL",
    // which would otherwise leave stray digits behind.
    const cleaned = head.replace(new RegExp(UNIT_PATTERN.source, "gi"), " ");

    const tokens = cleaned.match(new RegExp(NUMBER_PATTERN.source, "g"));
    if (!tokens || tokens.length === 0) continue;

    // Step 4: the last surviving number on the row is the reported result.
    const rawToken = tokens[tokens.length - 1];
    const value = toNumber(rawToken);
    if (value === null) continue;

    const unitMatch = line.match(UNIT_PATTERN);
    const unit = unitMatch ? canonicalUnit(unitMatch[1]) : definition.unit;
    const referenceRange = toReferenceRange(definition);
    const status = scoreBiomarkerStatus(value, referenceRange);

    let confidence = 0.7;
    if (unitMatch) confidence += 0.16;
    if (rangeMatch) confidence += 0.07;
    if (line.length < 12) confidence -= 0.12;
    if (unit === definition.unit) confidence += 0.05;
    // Deterministic per-line jitter keeps repeated values from looking identical.
    confidence += ((hashString(line) % 9) - 4) / 100;
    confidence = Math.min(0.99, Math.max(0.31, Number(confidence.toFixed(2))));

    return {
      id: `field-${hashString(`${definition.key}:${line}`).toString(36)}`,
      testName: definition.displayName,
      normalizedKey: definition.key,
      value,
      valueText: rawToken,
      unit,
      referenceRange,
      status,
      plainLanguageExplanation: buildExplanation(definition, value, unit, status),
      category: definition.category,
      confidence,
      matchedAlias: alias,
    };
  }

  return null;
}

/**
 * Extract every recognisable biomarker from a blob of OCR text. Duplicate
 * mentions keep the highest-confidence reading, mirroring how a human would
 * take the printed result column over a value repeated in a summary footer.
 */
export function parseReportText(text: string): ExtractedField[] {
  const byKey = new Map<string, ExtractedField>();

  for (const rawLine of text.split(/\r?\n/)) {
    const field = matchBiomarkerLine(rawLine);
    if (!field) continue;
    const existing = byKey.get(field.normalizedKey);
    if (!existing || field.confidence > existing.confidence) {
      byKey.set(field.normalizedKey, field);
    }
  }

  // Preserve dictionary order so panels read the way a lab prints them.
  return BIOMARKER_DICTIONARY.filter((definition) => byKey.has(definition.key)).map(
    (definition) => byKey.get(definition.key) as ExtractedField,
  );
}

/* ------------------------------------------------------------------ */
/* Simulated OCR                                                       */
/* ------------------------------------------------------------------ */

export interface OcrProgressEvent {
  /** 0 - 1 completion ratio for the progress bar. */
  ratio: number;
  step: string;
}

export interface OcrResult {
  text: string;
  confidence: number;
  engine: "direct-text" | "simulated";
}

/** Panel transcripts used when the uploaded file has no machine-readable text. */
export const SYNTHETIC_OCR_TRANSCRIPTS: Record<ReportCategory, string> = {
  blood_panel: [
    "SMARTMEDIC REFERENCE LABORATORIES",
    "Complete Blood Count & Glycemic Panel",
    "----------------------------------------------------------------",
    "Fasting Blood Sugar (FBS)          148     mg/dL      70 - 99      H",
    "Glycated Hemoglobin (HbA1c)        7.2     %          4.0 - 5.6    H",
    "Hemoglobin (Hb)                    11.8    g/dL       13.5 - 17.5  L",
    "Total Leukocyte Count (TLC)        8.9     x10^3/uL   4.0 - 11.0",
    "Platelet Count (PLT)               232     x10^3/uL   150 - 450",
    "Hematocrit (HCT)                   36.4    %          40 - 52      L",
    "Mean Corpuscular Volume (MCV)      86.2    fL         80 - 100",
    "Erythrocyte Sedimentation Rate     28      mm/hr      0 - 20       H",
    "----------------------------------------------------------------",
    "Specimen collected: whole blood EDTA / fluoride oxalate",
    "Interpretation is the responsibility of the referring physician.",
  ].join("\n"),
  renal_panel: [
    "SMARTMEDIC REFERENCE LABORATORIES",
    "Renal Function Panel",
    "----------------------------------------------------------------",
    "Serum Creatinine                   1.4     mg/dL      0.7 - 1.3    H",
    "Blood Urea                         31      mg/dL      7 - 20       H",
    "Estimated GFR (eGFR)               62      mL/min/1.73m2  90 - 120  L",
    "Serum Sodium (Na+)                 138     mmol/L     135 - 145",
    "Serum Potassium (K+)               4.6     mmol/L     3.5 - 5.1",
    "Serum Uric Acid                    7.8     mg/dL      3.4 - 7.0    H",
    "----------------------------------------------------------------",
    "Specimen collected: serum separator tube",
  ].join("\n"),
  lipid_profile: [
    "SMARTMEDIC REFERENCE LABORATORIES",
    "Fasting Lipid Profile",
    "----------------------------------------------------------------",
    "Total Cholesterol                  214     mg/dL      125 - 200    H",
    "LDL Cholesterol                    138     mg/dL      50 - 100     H",
    "HDL Cholesterol                    38      mg/dL      40 - 60      L",
    "Triglycerides                      186     mg/dL      50 - 150     H",
    "----------------------------------------------------------------",
    "12 hour fasting specimen confirmed.",
  ].join("\n"),
  thyroid_panel: [
    "SMARTMEDIC REFERENCE LABORATORIES",
    "Thyroid Function Panel",
    "----------------------------------------------------------------",
    "Thyroid Stimulating Hormone (TSH)  4.6     uIU/mL     0.4 - 4.0    H",
    "Total T3                           118     ng/dL      80 - 200",
    "Total T4                           8.4     ug/dL      5.0 - 12.0",
    "----------------------------------------------------------------",
  ].join("\n"),
  urinalysis: [
    "SMARTMEDIC REFERENCE LABORATORIES",
    "Urinalysis - Routine",
    "----------------------------------------------------------------",
    "C-Reactive Protein (CRP)           12      mg/L       0 - 5        H",
    "Serum Creatinine                   1.1     mg/dL      0.7 - 1.3",
    "----------------------------------------------------------------",
  ].join("\n"),
  general: [
    "SMARTMEDIC REFERENCE LABORATORIES",
    "General Chemistry Screen",
    "----------------------------------------------------------------",
    "Fasting Blood Sugar (FBS)          112     mg/dL      70 - 99      H",
    "Serum Creatinine                   1.0     mg/dL      0.7 - 1.3",
    "Hemoglobin (Hb)                    13.9    g/dL       13.5 - 17.5",
    "Total Cholesterol                  188     mg/dL      125 - 200",
    "C-Reactive Protein (CRP)           3       mg/L       0 - 5",
    "----------------------------------------------------------------",
  ].join("\n"),
};

export const OCR_PIPELINE_STEPS = [
  "Pre-processing scan (binarisation, deskew, denoise)",
  "Running optical character recognition",
  "Matching biomarker dictionary aliases",
  "Normalising units and reference ranges",
] as const;

function wait(ms: number): Promise<void> {
  return new Promise((resolve) => {
    setTimeout(resolve, ms);
  });
}

/** True when the browser can hand us the file's own text content. */
function isTextLike(fileName: string, mimeType: string): boolean {
  return /\.(txt|csv)$/i.test(fileName) || mimeType.startsWith("text/");
}

/**
 * Simulated OCR run. Reads real text when the file already contains it and
 * otherwise falls back to the synthetic transcript for the selected panel.
 */
export async function runSimulatedOcr(
  file: File,
  category: ReportCategory,
  onProgress?: (event: OcrProgressEvent) => void,
): Promise<OcrResult> {
  let directText: string | null = null;

  if (isTextLike(file.name, file.type)) {
    directText = await file.text();
  }

  for (let index = 0; index < OCR_PIPELINE_STEPS.length; index++) {
    onProgress?.({ ratio: index / OCR_PIPELINE_STEPS.length, step: OCR_PIPELINE_STEPS[index] });
    // A short, visible delay so the pipeline stages are legible in the demo.
    await wait(260);
  }

  onProgress?.({ ratio: 1, step: "Extraction complete" });

  if (directText && directText.trim().length > 0) {
    const fields = parseReportText(directText);
    const confidence = fields.length
      ? Number((fields.reduce((sum, field) => sum + field.confidence, 0) / fields.length).toFixed(2))
      : 0.4;
    return { text: directText, confidence, engine: "direct-text" };
  }

  const text = SYNTHETIC_OCR_TRANSCRIPTS[category];
  const fields = parseReportText(text);
  const confidence = fields.length
    ? Number((fields.reduce((sum, field) => sum + field.confidence, 0) / fields.length).toFixed(2))
    : 0.4;
  return { text, confidence, engine: "simulated" };
}

/* ------------------------------------------------------------------ */
/* Report summarisation                                                */
/* ------------------------------------------------------------------ */

export interface ReportSummary {
  total: number;
  inRange: number;
  outOfRange: number;
  critical: number;
  /** One-line, non-diagnostic headline for the summary card. */
  headline: string;
}

export function summariseFields(fields: ExtractedField[]): ReportSummary {
  const critical = fields.filter(
    (field) => field.status === "critical_low" || field.status === "critical_high",
  ).length;
  const outOfRange = fields.filter((field) => isOutOfRange(field.status)).length;
  const total = fields.length;

  let headline: string;
  if (total === 0) {
    headline = "No recognised lab values were found in this document.";
  } else if (critical > 0) {
    headline =
      `${critical} value${critical === 1 ? "" : "s"} sit well outside the reference range. ` +
      "Show this report to your treating physician for review.";
  } else if (outOfRange > 0) {
    headline =
      `${outOfRange} of ${total} values sit outside the reference range. ` +
      "Outside-range results are common and are always read alongside your history.";
  } else {
    headline = `All ${total} recognised values fall inside their reference ranges.`;
  }

  return { total, inRange: total - outOfRange, outOfRange, critical, headline };
}

/* ------------------------------------------------------------------ */
/* Longitudinal trend engine                                           */
/* ------------------------------------------------------------------ */

/**
 * Build per-biomarker history for one patient. Reports are sorted oldest-first
 * so the resulting series is directly chartable, and `previous` always refers
 * to the reading before the latest one.
 */
export function buildTrendSeries(
  reports: MedicalReport[],
  patientId: string,
  filterKeys?: string[],
): BiomarkerTrend[] {
  const relevant = reports
    .filter((report) => report.patientId === patientId)
    .slice()
    .sort((a, b) => new Date(a.reportDate).getTime() - new Date(b.reportDate).getTime());

  const series = new Map<string, BiomarkerTrend>();

  for (const report of relevant) {
    for (const field of report.extractedFields) {
      if (!field.normalizedKey) continue;
      if (filterKeys && filterKeys.length > 0 && !filterKeys.includes(field.normalizedKey)) continue;

      const point: TrendPoint = {
        date: report.reportDate,
        value: field.value,
        reportId: report.id,
      };

      const existing = series.get(field.normalizedKey);
      if (existing) {
        // A single report should contribute one point per biomarker; if the
        // same key repeats within one panel, the last reading wins.
        const last = existing.history[existing.history.length - 1];
        if (last && last.reportId === report.id) {
          existing.history[existing.history.length - 1] = point;
        } else {
          existing.history.push(point);
        }
        existing.latest = point.value;
        existing.status = field.status;
        existing.unit = field.unit;
        existing.plainLanguageExplanation = field.plainLanguageExplanation;
        continue;
      }

      series.set(field.normalizedKey, {
        normalizedKey: field.normalizedKey,
        testName: field.testName,
        unit: field.unit,
        category: field.category,
        referenceRange: field.referenceRange,
        history: [point],
        latest: point.value,
        previous: null,
        delta: null,
        deltaPct: null,
        direction: "stable",
        status: field.status,
        plainLanguageExplanation: field.plainLanguageExplanation,
      });
    }
  }

  for (const trend of series.values()) {
    const history = trend.history;
    if (history.length >= 2) {
      const latest = history[history.length - 1].value;
      const previous = history[history.length - 2].value;
      trend.previous = previous;
      trend.delta = Number((latest - previous).toFixed(2));
      trend.deltaPct = previous === 0 ? null : Number((((latest - previous) / previous) * 100).toFixed(1));
      trend.direction = classifyDirection(latest, previous, trend.referenceRange);
    }
  }

  return Array.from(series.values()).sort((a, b) => a.testName.localeCompare(b.testName));
}

/**
 * Direction of travel compared with the reference range. A change of less than
 * 2% of the range width is treated as stable so chart noise is not narrated.
 */
export function classifyDirection(
  latest: number,
  previous: number,
  range: ReferenceRange,
): "rising" | "falling" | "stable" {
  const width = Math.max(range.max - range.min, 1);
  const threshold = width * 0.02;
  const delta = latest - previous;
  if (Math.abs(delta) < threshold) return "stable";
  return delta > 0 ? "rising" : "falling";
}

/** Non-diagnostic narrative describing the direction of a trend. */
export function describeTrend(trend: BiomarkerTrend): string {
  if (trend.history.length < 2) {
    return "This is the first recorded result for this biomarker, so no comparison is available yet.";
  }
  const width = Math.max(trend.referenceRange.max - trend.referenceRange.min, 1);
  const changePct = Math.abs(((trend.latest - (trend.previous ?? trend.latest)) / width) * 100).toFixed(0);

  if (trend.direction === "stable") {
    return `The last ${trend.history.length} readings have stayed broadly level, moving less than ${
      trend.referenceRange.max === trend.referenceRange.min ? "the range width" : `${changePct}% of the reference range width`
    } between visits.`;
  }

  if (trend.direction === "rising") {
    return `Across the last ${trend.history.length} readings this value has moved upward, most recently by ${changePct}% of the reference range width. Direction of travel is not a diagnosis.`;
  }

  return `Across the last ${trend.history.length} readings this value has moved downward, most recently by ${changePct}% of the reference range width. Direction of travel is not a diagnosis.`;
}

/** Group extracted fields by panel category for the report screen sections. */
export function groupFieldsByCategory(fields: ExtractedField[]): { category: BiomarkerCategory; fields: ExtractedField[] }[] {
  const groups = new Map<BiomarkerCategory, ExtractedField[]>();
  for (const field of fields) {
    const list = groups.get(field.category) ?? [];
    list.push(field);
    groups.set(field.category, list);
  }
  return Array.from(groups.entries()).map(([category, grouped]) => ({ category, fields: grouped }));
}

export const BIOMARKER_CATEGORY_LABELS: Record<BiomarkerCategory, string> = {
  glycemic: "Blood Sugar",
  renal: "Kidney Function",
  hematology: "Blood Counts",
  lipid: "Cholesterol & Fats",
  thyroid: "Thyroid",
  electrolyte: "Minerals & Electrolytes",
  hepatic: "Liver Function",
  inflammatory: "Inflammation",
};
