-- ============================================================================
--  SmartMedic — initial schema
-- ============================================================================
--
--  Postgres (Supabase) schema for the hospital operations, shortage
--  intelligence, and report simplifier subsystems. It mirrors
--  `docs/database-schema.md` and the TypeScript domain model in `src/types.ts`.
--
--  Conventions
--  -----------
--  * Primary keys are TEXT and generated by the application, so an offline or
--    optimistic client write can be retried idempotently. Lookup tables that
--    have no independent identity (ward stock) use a natural composite key.
--  * Repeated child entities (prescriptions, invoice line items, payment
--    transactions, extracted report fields, ward holdings) are real tables,
--    not embedded documents, so they can be queried and aggregated in SQL.
--  * Embedded value objects that are always read and written with their parent
--    (allergies, emergency contact, admission, supplier profile) stay JSONB.
--  * Every table has RLS enabled with no permissive policy. The browser never
--    talks to these tables directly; all access goes through the API using the
--    service role, which bypasses RLS. The anon key therefore reads nothing.
--
--  Apply with:  supabase db push          (Supabase CLI)
--           or paste this file into the Supabase SQL editor.
-- ============================================================================


-- ----------------------------------------------------------------------------
-- 1. Workforce and identity
-- ----------------------------------------------------------------------------

create table if not exists staff (
  id                 text primary key,
  employee_id        text not null unique,
  full_name          text not null,
  role               text not null check (role in ('admin', 'doctor', 'nurse', 'receptionist', 'cashier')),
  department         text not null default '',
  email              text not null unique,
  contact_number     text not null default '',
  shift              text not null default 'morning' check (shift in ('morning', 'evening', 'night', 'rotational')),
  shift_start_hour   int  not null default 8 check (shift_start_hour between 0 and 23),
  created_at         timestamptz not null default now()
);

comment on table staff is 'Clinical and administrative workforce. One row per employee.';

-- ----------------------------------------------------------------------------
-- 2. Patients
-- ----------------------------------------------------------------------------

create table if not exists patients (
  id                   text primary key,
  mrn                  text not null unique,
  name                 text not null,
  dob                  date not null,
  gender               text not null check (gender in ('male', 'female', 'other')),
  blood_group          text not null default '',
  contact              text not null default '',
  email                text not null default '',
  allergies            jsonb not null default '[]'::jsonb,
  emergency_contact    jsonb not null default '{}'::jsonb,
  current_admission    jsonb not null default '{"isAdmitted": false}'::jsonb,
  chronic_conditions   text[] not null default '{}',
  resolved_conditions  text[] not null default '{}',
  registered_at        timestamptz not null default now()
);

create index if not exists patients_name_idx        on patients (name);
create index if not exists patients_mrn_idx         on patients (mrn);
create index if not exists patients_registered_idx  on patients (registered_at desc);

-- Links a Supabase auth user to the staff member or patient record they act as.
-- `auth.users` holds the credential; this table holds the authorisation profile.
-- Created after `patients` because it references it.
create table if not exists profiles (
  id            uuid primary key references auth.users (id) on delete cascade,
  email         text not null unique,
  full_name     text not null default '',
  role          text not null check (role in ('admin', 'doctor', 'nurse', 'receptionist', 'cashier', 'patient')),
  staff_id      text references staff (id) on delete set null,
  patient_id    text references patients (id) on delete set null,
  is_active     boolean not null default true,
  last_login    timestamptz,
  created_at    timestamptz not null default now(),
  -- Staff profiles must point at a staff row; patient profiles at a patient row.
  constraint profiles_identity_present check (
    (role = 'patient' and patient_id is not null)
    or (role <> 'patient' and staff_id is not null)
  )
);

create index if not exists profiles_staff_id_idx   on profiles (staff_id);
create index if not exists profiles_patient_id_idx on profiles (patient_id);


-- ----------------------------------------------------------------------------
-- 3. Formulary and stock
-- ----------------------------------------------------------------------------

create table if not exists medicines (
  id                        text primary key,
  sku                       text not null unique,
  brand_name                text not null,
  generic_name              text not null,
  category                  text not null,
  form                      text not null,
  strength                  text not null default '',
  unit                      text not null default 'unit',
  unit_price                numeric(12, 2) not null default 0,
  current_stock             int not null default 0,
  allocated_stock           int not null default 0,
  reorder_threshold         int not null default 0,
  economic_order_quantity   int not null default 0,
  safety_stock_days         numeric(6, 2) not null default 0,
  consumption_history       int[] not null default '{}',
  regional_alert            jsonb not null default '{}'::jsonb,
  supplier                  jsonb not null default '{}'::jsonb,
  therapeutic_alternatives  text[] not null default '{}',
  controlled_substance      boolean not null default false,
  last_restocked_at         timestamptz,
  created_at                timestamptz not null default now()
);

create index if not exists medicines_generic_name_idx on medicines (generic_name);
create index if not exists medicines_category_idx     on medicines (category);

-- Stock physically held per ward. The facility total is the sum of these rows,
-- which is what makes an inter-ward transfer stock-neutral by construction.
create table if not exists ward_stock (
  medicine_id  text not null references medicines (id) on delete cascade,
  ward         text not null,
  quantity     int  not null default 0 check (quantity >= 0),
  par_level    int  not null default 0,
  updated_at   timestamptz not null default now(),
  primary key (medicine_id, ward)
);

comment on table ward_stock is 'Per-ward holdings plus the ward par level used by the redistribution balancer.';


-- ----------------------------------------------------------------------------
-- 4. Front desk and clinical encounters
-- ----------------------------------------------------------------------------

create table if not exists appointments (
  id              text primary key,
  patient_id      text not null references patients (id) on delete cascade,
  doctor_id       text not null references staff (id),
  department      text not null default '',
  scheduled_for   timestamptz not null,
  reason          text not null default '',
  status          text not null default 'scheduled'
                    check (status in ('scheduled', 'checked_in', 'in_consult', 'completed', 'cancelled', 'no_show')),
  acuity          text not null default 'routine' check (acuity in ('critical', 'urgent', 'standard', 'routine')),
  triage_notes    text not null default '',
  queue_position  int,
  created_at      timestamptz not null default now()
);

create index if not exists appointments_patient_idx on appointments (patient_id);
create index if not exists appointments_doctor_idx  on appointments (doctor_id);
create index if not exists appointments_day_idx     on appointments (scheduled_for);

create table if not exists treatments (
  id                 text primary key,
  patient_id         text not null references patients (id) on delete cascade,
  doctor_id          text not null references staff (id),
  diagnosis          text not null default '',
  icd10_code         text not null default '',
  linked_report_ids  text[] not null default '{}',
  notes              text not null default '',
  created_at         timestamptz not null default now()
);

create index if not exists treatments_patient_idx on treatments (patient_id);
create index if not exists treatments_doctor_idx  on treatments (doctor_id);

create table if not exists prescriptions (
  id               text primary key,
  treatment_id     text not null references treatments (id) on delete cascade,
  medicine_id      text not null references medicines (id),
  drug_name        text not null,
  dosage           text not null default '',
  frequency        text not null default 'once_daily',
  duration_days    int  not null default 1,
  quantity         int  not null default 0,
  route            text not null default 'oral',
  instructions     text not null default '',
  substitute_for   text,
  dispense_status  text not null default 'pending'
                     check (dispense_status in ('pending', 'dispensed', 'substituted', 'cancelled')),
  stock_advisory   text,
  ordinal          int not null default 0
);

create index if not exists prescriptions_treatment_idx on prescriptions (treatment_id);
create index if not exists prescriptions_medicine_idx  on prescriptions (medicine_id);

create table if not exists administrations (
  id               text primary key,
  prescription_id  text not null,
  patient_id       text not null references patients (id) on delete cascade,
  medicine_id      text not null,
  drug_name        text not null,
  dose             text not null default '',
  route            text not null default 'oral',
  scheduled_for    timestamptz not null,
  status           text not null default 'given'
                     check (status in ('given', 'held', 'refused', 'missed')),
  administered_at  timestamptz,
  administered_by  text,
  site             text,
  notes            text not null default '',
  vitals_id        text
);

create index if not exists administrations_patient_idx  on administrations (patient_id);
create index if not exists administrations_schedule_idx on administrations (scheduled_for);

create table if not exists vitals (
  id                text primary key,
  patient_id        text not null references patients (id) on delete cascade,
  recorded_by       text not null default '',
  recorded_at       timestamptz not null default now(),
  temperature_c     numeric(4, 1),
  heart_rate_bpm    int,
  systolic          int,
  diastolic         int,
  respiratory_rate  int,
  spo2              int,
  pain_score        int,
  notes             text not null default ''
);

create index if not exists vitals_patient_idx on vitals (patient_id, recorded_at desc);


-- ----------------------------------------------------------------------------
-- 5. Revenue cycle
-- ----------------------------------------------------------------------------

create table if not exists invoices (
  id              text primary key,
  invoice_number  text not null unique,
  patient_id      text not null references patients (id) on delete cascade,
  cashier_id      text not null default '',
  tax_pct         numeric(5, 2) not null default 0,
  payment_status  text not null default 'unpaid'
                    check (payment_status in ('unpaid', 'partially_paid', 'paid', 'refunded')),
  notes           text not null default '',
  created_at      timestamptz not null default now()
);

create index if not exists invoices_patient_idx on invoices (patient_id);
create index if not exists invoices_status_idx  on invoices (payment_status);

create table if not exists invoice_items (
  id           text primary key,
  invoice_id   text not null references invoices (id) on delete cascade,
  item_type    text not null default 'consultation',
  description  text not null default '',
  quantity     int  not null default 1,
  unit_price   numeric(12, 2) not null default 0,
  ordinal      int not null default 0
);

create index if not exists invoice_items_invoice_idx on invoice_items (invoice_id);

create table if not exists payment_transactions (
  id                text primary key,
  invoice_id        text not null references invoices (id) on delete cascade,
  payment_method    text not null
                      check (payment_method in ('cash', 'credit_card', 'debit_card', 'upi', 'insurance_claim')),
  amount_paid       numeric(12, 2) not null default 0,
  reference         text not null default '',
  processed_at      timestamptz not null default now(),
  processed_by      text not null default ''
);

create index if not exists payment_transactions_invoice_idx on payment_transactions (invoice_id);


-- ----------------------------------------------------------------------------
-- 6. Medical report simplifier
-- ----------------------------------------------------------------------------

create table if not exists medical_reports (
  id                     text primary key,
  patient_id             text not null references patients (id) on delete cascade,
  uploaded_by            text not null default '',
  uploaded_by_role       text not null default 'patient',
  file_name              text not null default '',
  file_mime_type         text not null default '',
  file_size_bytes        bigint not null default 0,
  report_category        text not null default 'general',
  report_date            timestamptz not null default now(),
  ocr_extraction_status  text not null default 'completed'
                           check (ocr_extraction_status in ('pending', 'processing', 'completed', 'failed')),
  ocr_confidence         numeric(4, 3) not null default 0,
  raw_ocr_text           text not null default '',
  medical_disclaimer     text not null default '',
  doctor_notes           text not null default '',
  archived               boolean not null default false,
  resolved_reason        text,
  created_at             timestamptz not null default now()
);

comment on table medical_reports is
  'Parsed report metadata and simulated-OCR transcript. The original document bytes are deliberately not retained.';

create index if not exists medical_reports_patient_idx on medical_reports (patient_id, report_date desc);

-- One row per biomarker line extracted from a report. `normalized_key` is the
-- join used to build longitudinal trends across a patient's reports.
create table if not exists report_fields (
  id                          text primary key,
  report_id                   text not null references medical_reports (id) on delete cascade,
  ordinal                     int not null default 0,
  test_name                   text not null,
  normalized_key              text not null default '',
  value                       numeric(14, 4),
  value_text                  text not null default '',
  unit                        text not null default '',
  ref_min                     numeric(14, 4),
  ref_max                     numeric(14, 4),
  ref_text                    text not null default '',
  ref_critical_low            numeric(14, 4),
  ref_critical_high           numeric(14, 4),
  status                      text not null default 'unknown',
  plain_language_explanation  text not null default '',
  category                    text not null default 'hematology',
  confidence                  numeric(4, 3) not null default 0,
  matched_alias               text not null default ''
);

create index if not exists report_fields_report_idx on report_fields (report_id, ordinal);
create index if not exists report_fields_key_idx    on report_fields (normalized_key);


-- ----------------------------------------------------------------------------
-- 7. Shortage intelligence and governance
-- ----------------------------------------------------------------------------

-- Supply-side decisions taken against an engine recommendation. Live proposals
-- are derived on read; this table is the immutable decision ledger.
create table if not exists transfer_proposals (
  id                   text primary key,
  medicine_id          text not null,
  drug_name            text not null default '',
  from_ward            text not null,
  to_ward              text not null,
  quantity             int  not null default 0,
  surplus_at_source    int  not null default 0,
  deficit_at_target    int  not null default 0,
  rationale            text not null default '',
  estimated_sps_drop   numeric(8, 2) not null default 0,
  wards_recovered      int not null default 0,
  status               text not null default 'proposed' check (status in ('proposed', 'approved', 'rejected')),
  decided_at           timestamptz,
  decided_by           text
);

create index if not exists transfer_proposals_medicine_idx on transfer_proposals (medicine_id);
create index if not exists transfer_proposals_decided_idx  on transfer_proposals (decided_at desc);

create table if not exists alerts (
  id               text primary key,
  medicine_id      text not null,
  drug_name        text not null default '',
  tier             text not null,
  sps              numeric(8, 2) not null default 0,
  message          text not null default '',
  created_at       timestamptz not null default now(),
  acknowledged     boolean not null default false,
  acknowledged_by  text,
  acknowledged_at  timestamptz
);

create index if not exists alerts_acknowledged_idx on alerts (acknowledged);

-- Append-only ledger. Every clinical, supply and financial write appends here,
-- which is what gives the prototype a defensible audit trail.
create table if not exists audit_log (
  id          text primary key,
  at          timestamptz not null default now(),
  actor_id    text not null default '',
  actor_name  text not null default '',
  actor_role  text not null default 'admin',
  action      text not null default '',
  target      text not null default '',
  detail      text not null default ''
);

create index if not exists audit_log_at_idx       on audit_log (at desc);
create index if not exists audit_log_actor_idx    on audit_log (actor_id);
create index if not exists audit_log_action_idx   on audit_log (action);

-- Human-readable ID sequence backing `appointment-0007` style identifiers.
create table if not exists counters (
  key    text primary key,
  value  int not null default 0
);


-- ----------------------------------------------------------------------------
-- 8. Row level security
-- ----------------------------------------------------------------------------
--
-- The SPA never queries these tables with the anon key: it calls the API, which
-- authenticates the caller's Supabase JWT and then reads and writes with the
-- service role. Enabling RLS with no policies therefore locks every table to
-- the API surface. RLS is intentionally left unforced so the table editor and
-- SQL console (which connect as the owner) can still inspect rows.
-- ----------------------------------------------------------------------------

do $$
declare
  target text;
begin
  foreach target in array array[
    'staff', 'profiles', 'patients', 'medicines', 'ward_stock', 'appointments',
    'treatments', 'prescriptions', 'administrations', 'vitals', 'invoices',
    'invoice_items', 'payment_transactions', 'medical_reports', 'report_fields',
    'transfer_proposals', 'alerts', 'audit_log', 'counters'
  ]
  loop
    execute format('alter table %I enable row level security', target);
  end loop;
end $$;
